[package]
name = "aur-depends"
version = "0.11.0"
authors = ["morganamilo <m?organamilo@gmail.com>"]
edition = "2018"

description = "A libary for resolving aur dependencies"
homepage = "http://github.com/Morganamilo/aur-depends"
repository = "http://github.com/Morganamilo/aur-depends"
documentation = "https://docs.rs/aur_depends"
license = "GPL-3.0"
keywords = ["archlinux", "pkgbuild", "arch", "aur"]
exclude = ["tests"]

[dependencies]
alpm = "1.1.0"
alpm-utils = "0.6.0"
log = "0.4.11"
raur = "4.0.0"
bitflags = "1.2.1"

[dev-dependencies]
async-trait = "0.1.41"
simplelog = "0.8.0"
tokio = { version = "0.2", features = ["macros"]}

[features]
git = ["alpm/git", "alpm-utils/git"]
rustls = ["raur/rustls"]
default = ["raur/default"]
