[package]
name = "aur-depends"
version = "0.2.1"
authors = ["morganamilo <morganamilo@gmail.com>"]
edition = "2018"

description = "A libary for resolving aur dependencies"
homepage = "http://github.com/Morganamilo/aur-depends.rs"
repository = "http://github.com/Morganamilo/aur-depends.rs"
documentation = "https://docs.rs/aur_depends"
license = "GPL-3.0"
keywords = ["archlinux", "pkgbuild", "arch", "aur"]
exclude = ["tests"]

[dependencies]
alpm = "0.6.0"
log = "0.4.8"
raur = { version = "2.0.0", default-features = false }
raur-ext = "1.1.1"
alpm-utils = "0.1.1"
bitflags = "1.1.0"

[dev-dependencies]
simplelog = "0.7.1"

[features]
git = ["alpm/git", "alpm-utils/git"]
rustls = ["raur/rustls", "raur-ext/rustls"]
#default = ["raur/default"]
