[package]
name = "aur-depends"
version = "0.4.0"
authors = ["morganamilo <morganamilo@gmail.com>"]
edition = "2018"

description = "A libary for resolving aur dependencies"
homepage = "http://github.com/Morganamilo/aur-depends.rs"
repository = "http://github.com/Morganamilo/aur-depends.rs"
documentation = "https://docs.rs/aur_depends"
license = "GPL-3.0"
keywords = ["archlinux", "pkgbuild", "arch", "aur"]
exclude = ["tests"]

[dependencies]
alpm = "0.9.0"
log = "0.4.11"
raur = { version = "3.0.1", default-features = false }
raur-ext = { version = "2.0.0", default-features = false }
alpm-utils = "0.2.1"
bitflags = "1.2.1"

[dev-dependencies]
simplelog = "0.8.0"

[features]
git = ["alpm/git", "alpm-utils/git"]
rustls = ["raur/rustls", "raur-ext/rustls"]
default = ["raur/default", "raur-ext/default"]
